//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2ODBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int id_factura { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_lectura { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public decimal monto_total { get; set; }
        public string estado { get; set; }
        public string detalle_consumo { get; set; }
    
        public virtual Lectura Lectura { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
