//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2ODBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        public int id_incidencia { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_medidor { get; set; }
        public string tipo_incidencia { get; set; }
        public System.DateTime fecha_reporte { get; set; }
        public string estado { get; set; }
        public string detalle_resolucion { get; set; }
    
        public virtual Medidor Medidor { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
