//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2ODBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lectura()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int id_lectura { get; set; }
        public Nullable<int> id_medidor { get; set; }
        public System.DateTime fecha_lectura { get; set; }
        public decimal lectura_anterior { get; set; }
        public decimal lectura_actual { get; set; }
        public Nullable<decimal> consumo { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Medidor Medidor { get; set; }
    }
}
