//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2ODBF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaAguaEntities1 : DbContext
    {
        public SistemaAguaEntities1()
            : base("name=SistemaAguaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Incidencia> Incidencia { get; set; }
        public virtual DbSet<Lectura> Lectura { get; set; }
        public virtual DbSet<Medidor> Medidor { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Recibo> Recibo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
